create table request(
		no smallint auto_increment primary key,
		name char(20) not null,
		company char(20),
		tel1 smallint unsigned not null,
		tel2 smallint unsigned not null,
		tel3 smallint unsigned not null,
		mobile1 smallint unsigned not null,
		mobile2 smallint unsigned not null,
		mobile3 smallint unsigned not null,
		email1 varchar(20),
		email2 varchar(20),
		cost tinyint unsigned,
		page tinyint unsigned,
		title varchar(50),
		contents text,
		bench_01 varchar(50),
		bench_02 varchar(50),
		bench_03 varchar(50)
);
