create table MadLog_exp_client (
		id char(20) not null primary key,
		project_name varchar(30),
		tel1 smallint unsigned,
		tel2 smallint unsigned,
		tel3 smallint unsigned,
		fax1 smallint unsigned,
		fax2 smallint unsigned,
		fax3 smallint unsigned,
		mobile1 smallint unsigned,
		mobile2 smallint unsigned,
		mobile3 smallint unsigned,
		addr varchar(100),
		email1 varchar(20),
		email2 varchar(20),
		charger varchar(20),
		position varchar(20),
		server_url varchar(50),
		server tinyint unsigned,
		db tinyint unsigned,
		language tinyint unsigned,
		start_date date,
		finish_date date,
		contract_money bigint unsigned,
		input_complement tinyint unsigned,
		contents text
);
